name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.21.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b818e4ff0565105091d1c23f3c3d821d623c464f1135fb7f3e93491c7c8f4063"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
