name = "LunarFox"
author = "OrzMiku"
version = "1.2.4+mc1.21.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0640e1e0b8322aa6f18f8303ba83e55f9d9a1547f791960509f2455f177869bc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
