hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "7dafa18e710692bce1763cb36b73088ad7688039078eeb3ee396b800bb3360ce"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "58c9e639e6458fdcdd201f080187df717242571a32d6406479b7624468ca66e9"

[[files]]
file = "config/betteradvancements.json"
hash = "e5f6ace68c722b5e4ea32f9935ca0b8dfbea1d22f1b8599a339bde0456605973"

[[files]]
file = "config/c2me.toml"
hash = "6cc49905c1c8ff23683cfa9509bfd0576ddf2a315554845286f4f1eb2c4f85d9"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "0c84b9f026021e9aeb87cd2400139e6e206d479bf52a22f0138addd883d466bc"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/inventoryhud-client.toml"
hash = "a7b25bbe74ba531773d630d46b58bff19f41740b24278f9954ddd604411d1de6"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "8fa033afa83e6b5123c11bb293b0a5e632b4f76b2ca7d651350179fd435462c9"

[[files]]
file = "config/iris_shader_folder.properties"
hash = "1a5d6fcabb22ac0718408b7ff05e298e719ffe855586df320bf0acbe6d3d0581"

[[files]]
file = "config/minihud.json"
hash = "435f7811c796b2352fee74985081994d69f881f9f0b6a0499ba39fbc40ee3f0b"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "5cb23400baacc7b307f687a19b966c0aa6861e7b157167dc02fd416e5a9219fa"

[[files]]
file = "config/moreculling.toml"
hash = "5cf6393f2eb20dc325b389aad51cab186c01a06956013138500de9235da31b0e"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "c550f46ad5ec34377e2b77a84f553ef1ac02bd9515219a8b4c0239ce036a966a"

[[files]]
file = "config/smoothswapping.json"
hash = "f4c337eebd35fecae160aa06274e32df1327ed42565a818797a508c18d6dbcfd"

[[files]]
file = "config/sodium-options.json"
hash = "925c54884e5bb35cd962cc021219ee647f30dd68833109d396da9fb8545066f4"

[[files]]
file = "config/tweakeroo.json"
hash = "61959e34930508cde414a11b937b544727ba3aa18712751b510ad5cec99eebeb"

[[files]]
file = "config/xaerominimap.txt"
hash = "805d874877e6bb962ac09c250b3d2a084ec599b2242dd1fa36860623c2024890"

[[files]]
file = "config/xaeroplus.txt"
hash = "b7c5f9eae2724e1da18af59e9369ddfd9d7b1c437ec6517603f22f0ff3bfcd3a"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "b0df40e07391a60294d7bffb9772cabe8096d61c41c8680fbfad927d3a6a5a6b"

[[files]]
file = "icon.png"
hash = "7ed2443085370e3427bd3e803037356811af68ad3fc131947a89cc89f2103fc7"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7b5fba1b2499c191160be6b1b01c54ace077ae7d3c5228ae4af4d360e3d0a336"
metafile = true

[[files]]
file = "mods/acceleratedrendering.pw.toml"
hash = "fffa6d9107ab284df6ffb7f155d75b778ffe99d96382d6baed4bba8d89de0b1c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "4f20967ee66eb96cbcfaa63bea9d3424ac45b7db414c9a491f31c86012f34fb5"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "be28a9ff89c60140b2983eb91089e77bec90bc5a0379c25472be01cb14dcbb97"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5ea9fb9ea7bf0fed99866d9dc20ffc907c6f6cf203dddeca9dda01ee475cfc37"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "cc2e6dda94a7a6f5487843cafe569d8044bf9482cbf03f062cf4595f1fb05281"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "e1f1588b18947699ddc9b4f7c5b5406c5559155b8cb52dcd0f203c07c31cd0b8"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "a850075a3b7e380701f0291f6151487d0a05bb54db125c8edf9f96a696b73188"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "ba58df8c82fc920a316a3ad2f8d52e985e34cd09713487ccbb5ea778b6168c2d"
metafile = true

[[files]]
file = "mods/bocchud.pw.toml"
hash = "5dfe7d124eccb5df2b23a42670182889f95a4a3ed893ed41d79e65e5c4c7e6ae"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
hash = "683dbecfc509287f8a28fe2a73f180e5a488b9751c61a5a297c581287c5a57da"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "c27af69a7c64206beff3e59c671934d4eb9a3dc65fd589609c5e6f6bb60421bb"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "5278f89a988809a740f83918bf3114bf3c1631d0eb471d534f6d67c3f536ad19"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "48cbc3da595efc9c3e04fb06bf9ba71861fcbd2e70dc1596a38ccb14b5179edc"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "bd005d9f92131c7c4a88a081aa5368c482eec2cb410d14ab245a2f081e9e1ffb"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6b5fa0d3a684cf6cf33f1399c2b4bdbee34dbe362548808315b488ac172e2ada"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f48d8d1f04f68dc8e6cac4ed4768790fa7ab35ee23c2aaed5391d862c6043eab"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "18e6869e7b42841227824563fc774e2e268040d88167b0ab47187298f29b0bb6"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "cd77d7f479a925f2c5147a9e4103a7c35c19292bf3a3144a59ecbb2905ceba62"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "e5125f8f2709fd20f8182fade3d7f9e7129872c63f042c5489c6eba4733b6b49"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "2741b6724a6c7d625c1c9e647a8d20ab89cd4a3975c18706da30771754c00510"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
hash = "574e4be5a4194cf6a44a5d064e3734dfbaac911c3caebfdf722ed7c35ff5215e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "2e76c80ff830074b19c38520160b00713985e6e9df7a3ff180116e3a73bb8937"
metafile = true

[[files]]
file = "mods/forgematica.pw.toml"
hash = "a8bdefffee0ac7aab23ffd3ffdc2e7ce8a36048828dffdb3ae1911c82d84a1b0"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ec1bd5b80399287ca33a113086bee9d5697b7e673c9f593e5a1aeca4c9bad4c9"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "11c4ac6932c14f3ad5a2c63d7f39eee1e9a2a91ffc079d5bd917c9aa381abdfb"
metafile = true

[[files]]
file = "mods/held-item-info-neoforge.pw.toml"
hash = "e381614dc48bb664b1fd1765ae69ec4ee05babad8b847fe1a1b6bb8fd2180fcc"
metafile = true

[[files]]
file = "mods/imblocker-original.pw.toml"
hash = "91a73d149ab0a877d9a0ab5c10b0938ca049f23e23632db31aea834cd002252c"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "8f1bcd5781c09e0929dd109bbd7cbb4636641dee96441cf125f279f328708268"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "19997fc3233640cda64d2fbe3eb0c01c51910101cc67ad078fa1c9d9c7374703"
metafile = true

[[files]]
file = "mods/iris-shader-folder.pw.toml"
hash = "9c2252080ad469a3fed3e5f48f58cb8daac2ce241963836687cbc3972bc2b847"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/itemphysic-lite.pw.toml"
hash = "8d03c992c84b3041ff36a793a54f09ccd0985574b120c3de8e67263e0fa9fb04"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/justenoughcharacters.pw.toml"
hash = "ff38060ad9c85f3a166c4a95049c202637e7be9586134bb95094a61564ea3b8f"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "e5e4c1204b278535538d4e45b3c65e577b37cfb3c17ebae5d136404d6b37fbfb"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9236940eafe8e97819f093c3c77236ee47de3b7f97a17f3fcf31114034962611"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "170212f0b41fc84d5d75248ad0f16f21be8079494e03c517d985fe9034196cff"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/mafglib.pw.toml"
hash = "58020b79db83e23e241b662de7ba078e80acd4c36d3825c2a2848f99c4f0e32e"
metafile = true

[[files]]
file = "mods/mcwifipnp.pw.toml"
hash = "9c3bf2d00b08908a8c31b1b330a4a44cf9a6814776571ead39d5bac889fc247f"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "9dff522b00f5269538d0351536f34b22384996de30be454ef1369f1b1e5c1aeb"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7713cc82e1ea68848508ed5c1a1c7bd1a832c0bcc97c96865891b9a2a33aa825"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6f0dcbcffd4400c6cef07f1eeb48cdc25bac0fa01270936feab4c549aff4738e"
metafile = true

[[files]]
file = "mods/modern-ui.pw.toml"
hash = "1b8e7dc5dca00aea85c9f1b42119d9a6e09ec69c62651035149fcfd26f0422e5"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/neoforge-carpet.pw.toml"
hash = "7513ef48054b3d2d72aace3d3f39440c6b533ba518ea8d4cfaf1fb6d30dd9e7d"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "b3e831b3e4d6ddbf23806b0fec6087eca264af1ebc04e747c89024972aaa8607"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "99813592c09351cb6340d8519d919e0d2d0b2f8073c3fe6833e7d846616bf5f2"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "49c0bacf8e4cb3ade6c384ad379282f92d7fa3075f2affd8e3093feb685288dd"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "f9b03a8d6466455294d823b23712e43bb9f26cb621d27b6134c150cf64cd671b"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "f527c21279cbfc2025d9cdf8267fe22cd43b42a2f994fc4ae0d76c069a844387"
metafile = true

[[files]]
file = "mods/resource-gamma-utils.pw.toml"
hash = "16e91410de2e9312243d8953d63a96c901af7ed872a4a4fa31746c6804c4b214"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "321ef3db87c1827e785b761e04bd2576d2597492653f8b92eda2278eed4b21cc"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "b78044fd79ce21750d05dc61b6aede33c4b87cdc16a26f5aff472d4f73ab623c"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "2c1661e65d47c2942d2c3e926698d0762672224f1925c7f25105b964ce25b093"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "2507dd9242e994ec7a0b21255b0b51a91bf9e0e51b060defe7bf7f8fa1f04b53"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/smooth-swapping.pw.toml"
hash = "278ada4b395307fab4b7451ed7d13bde46a4b48ae6d3f9cf8cd78ecb82da1108"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "c5687771065e4a43266b38018cbdf142b216916dd73aa6532b8282e3d0f06b9c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "62bd7012826fdcccf17a089055be67f87fb7335c88e73efc52bc9e51a1bf3188"
metafile = true

[[files]]
file = "mods/tweakerge.pw.toml"
hash = "acb2e26fea2b6353f80cdf9909cd9362262b55d8ba6ae26ca0e78016bfaa3109"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "51ba2572bd0a277cce914941123bb0d055fcbb05dd373d4d921bcb8ddb554289"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "03636eaa65730e65639d1e5c560045017117876837c0a8c48fe0798ca1f7854e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64eaf7478e42d5143f4feeee87c56f779f4c3523f9fb06d8342484d36aa4442b"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true

[[files]]
file = "options.txt"
hash = "18d6cbbf3c812f0f3cc48eec56964b895fdfa57ce58616122aeee07e99371162"

[[files]]
file = "resourcepacks/acaciachan-xaero-map-translation.pw.toml"
hash = "a763f371804ad4bd8d571f1a000fba61a6eaa2f295a347683fd10063110b4d12"
metafile = true

[[files]]
file = "resourcepacks/spbr.pw.toml"
hash = "1cc27f5b9dfe2a8cd3b8d43df0466b8086300e7cbd516785daf8910cee502f6e"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "616d949ae5c0ce479f9fe651a5c559f2e02b22e5b5762230101bd2213c7aa8c1"
metafile = true

[[files]]
file = "shaderpacks/Sundial-Lite-277a82a.zip"
hash = "9e8a672257f3c0c33fb62109c5d7e235129049687f04c05ce12f8a4d01a3c624"

[[files]]
file = "shaderpacks/Sundial-Lite-MMCO_v0.2.18.zip"
hash = "e0f248b2ffd1170b4032a002746883d977751b4c9468e92c68a6d80d78af1bd6"

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "f4fb7685cf5f1f07eb5b07b0dd7ea211e46e249cb3a78237358d27c3db1dea2b"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true
