name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+mc1.21.1-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85e9cbc0ac32017de425420993d873be83663190b6595a09c1ba45936463512b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
