name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+mc1.21.1-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe734b739c6f1c2bb62c5548b6b531fba3c0816bebad87c4c72ae5ed9a4cb657"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
