name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+mc1.21.1-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2f6629a651de1cd3a0babc3492dc1c8dab67d470f733259a75136cabae53f6f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
