name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+mc1.21.1_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dbfe7da7de2320257c1e39f85a11a02d5c159b87b5ed6322c5bda110220fa2d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
