name = "LunarFox"
author = "OrzMiku"
version = "1.0.2+mc1.21.1-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72f7b5b8693e1a47fec98f95f852e66203e1e83a7414c8eab9f2f48adfa1c9ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
