name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+mc1.21.1-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d503a7b9eeacde95c741de3252b5ecd10ae54827081642255491e626b7044f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
