hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "7dafa18e710692bce1763cb36b73088ad7688039078eeb3ee396b800bb3360ce"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "58c9e639e6458fdcdd201f080187df717242571a32d6406479b7624468ca66e9"

[[files]]
file = "config/betteradvancements.json"
hash = "e5f6ace68c722b5e4ea32f9935ca0b8dfbea1d22f1b8599a339bde0456605973"

[[files]]
file = "config/bocchud.json"
hash = "435f7811c796b2352fee74985081994d69f881f9f0b6a0499ba39fbc40ee3f0b"

[[files]]
file = "config/c2me.toml"
hash = "6cc49905c1c8ff23683cfa9509bfd0576ddf2a315554845286f4f1eb2c4f85d9"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "95431df060f44a4812fdb7fae743f0909522053550578eae056dbd0585bf6120"

[[files]]
file = "config/embeddium-options.json"
hash = "925c54884e5bb35cd962cc021219ee647f30dd68833109d396da9fb8545066f4"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/inventoryhud-client.toml"
hash = "a7b25bbe74ba531773d630d46b58bff19f41740b24278f9954ddd604411d1de6"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "8fa033afa83e6b5123c11bb293b0a5e632b4f76b2ca7d651350179fd435462c9"

[[files]]
file = "config/iris_shader_folder.properties"
hash = "1a5d6fcabb22ac0718408b7ff05e298e719ffe855586df320bf0acbe6d3d0581"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "5cb23400baacc7b307f687a19b966c0aa6861e7b157167dc02fd416e5a9219fa"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "c550f46ad5ec34377e2b77a84f553ef1ac02bd9515219a8b4c0239ce036a966a"

[[files]]
file = "config/tweakerge.json"
hash = "61959e34930508cde414a11b937b544727ba3aa18712751b510ad5cec99eebeb"

[[files]]
file = "config/xaerominimap.txt"
hash = "805d874877e6bb962ac09c250b3d2a084ec599b2242dd1fa36860623c2024890"

[[files]]
file = "config/xaeroplus.txt"
hash = "b7c5f9eae2724e1da18af59e9369ddfd9d7b1c437ec6517603f22f0ff3bfcd3a"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "b0df40e07391a60294d7bffb9772cabe8096d61c41c8680fbfad927d3a6a5a6b"

[[files]]
file = "icon.png"
hash = "7ed2443085370e3427bd3e803037356811af68ad3fc131947a89cc89f2103fc7"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "b2ed80a95132518a9a6d52a487a7ddcc5b73904a335af5274d912c78fda3a649"
metafile = true

[[files]]
file = "mods/acceleratedrendering.pw.toml"
hash = "87c84f6614ff51665568985fa35fa69d88a7d2494da770bbf3d0fb16343b11ac"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "786d07a05c5cc3ae4b2ee78aa95555017a411450a7a0e2328660b9ce3a47943a"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7eb6b5ee57865d6221be3c428f5a0c4e449f4c86920e9f8736b4f755d7822edf"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1b31cb793a692d9f692b233eab37e6fed156f7b05c4a2080a75ea6c06c38c178"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "6d369d90dac6730c6faa243bf73d00d9945e2a932c9c031eb7619d979eaebe8d"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "777eb31bb0687b66bec8f9e5c3cf3b43030add8fcdf3f0c7db07f0e30208a820"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "58396d4cd2dee0f75cf56def0ab301021b6e09a83bd2564212152f0a73433568"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "ccd718340ef692d4e4c013813f72c5498c31b033d7ace29dadf098d1cb905614"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "ecbab69ff127ce3fdc9a50bcc3ec344eb1ac6929c073ee16839a8f9d3e206f9c"
metafile = true

[[files]]
file = "mods/bocchud.pw.toml"
hash = "8a8d5173c74824a1ae312d7a22e3fc6a5a3312e48f034f2be83ee345e749eda3"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "e271d3f6a204153ea55370a2fab28e6ed329ab020d05fc9b03a5163065384dec"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "852ee3d5dea735c0c8f4c030edb06164863e7d27eef535c697f86a8b20a1cff0"
metafile = true

[[files]]
file = "mods/connectored-c2me-(c2me-fork-for-connector).pw.toml"
hash = "29707b0d591793d493d2378181d247358c00fc51bd77668b63cda8aa6f8c343d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8cea6a7ec6b151f92a3a62261530bb1aefe173ad19840c0319aa10e0d8ab2386"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "4063abe583282834b2f78e3b3e6b9ee4d231a680f74c020e405a4ef196f21ee4"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "408e7f666994cbf9aff9befa4d4e9ef33eadf913760cabe3d16fb5df3b166bd5"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "3497e48c52866fe536932d77fbb5cb1793d4e268e52873f1ca5c1e961b777814"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c5ea75feae4d340856611f78a29e6f1f0b7e707bfe43847f11d25fac1769dee7"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "ea969a2c6d77b5e7c8bd8ab8fe52c0c46de676a9cc517f014965699d90c5ed92"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "5ac6fe9a921d8fa00456ec2e18da02ede5c0da424c5c5b57da1206feeac40ff6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7b32032b0892b53e1e5daf5410b78b4d98b7bdcbe2184f1d643098de36674865"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "4c5ec7476521092a74d8ae1b894e44903a3d7834898674294f0ce4ddb040b251"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "1951c8531662d23b66b8b3d88ff6951a47756f08abe176a56e2d7e98c78f4f5e"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "890237857f20739f335cabccfcf0af77bdca305e5fb776f1484c30086520d3dc"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "2db3a1221517a6d4344b7359463d115461844f12b001edd8d19395eecc12a7f3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "06580e84bd3c27a84c743ebe0c45e3bd7ce6e1b6377e39f15774634a7663130b"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
hash = "710a1cc6aa24e68ba6c4cb93d686b17688d093ff7baecc1d0fa3036a3426ff35"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/flerovium.pw.toml"
hash = "57b4b547bb2a5236b6ff1c5b4feedc8853891d7786751f6b75397319794fd301"
metafile = true

[[files]]
file = "mods/forgematica.pw.toml"
hash = "e3017a1b798d295fb73a1b63b1bf9be067adfcf7a79fdcbc919bb8ffddbdbcb9"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2a2f2168bf03bfa3034ad9583588676c5d66b6f7c767df9fe259ab55350792d2"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "e47b4547b51bcd116aa7734ccd185a4edbcec4caf7ff80ef195ada4b727f5f15"
metafile = true

[[files]]
file = "mods/held-item-info-neoforge.pw.toml"
hash = "2c927e80a5b0610a8ca51f2a594f0e43706f239506f774359adfa12a15e48acd"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "2514cf5b79023dea4f80446a03bfef5ddfaa4cc3a463abb49fd8a16c891ac620"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "4836e47d6edbbf392ad4154699585d67712165710e23e11c70590e793a67f389"
metafile = true

[[files]]
file = "mods/iris-shader-folder.pw.toml"
hash = "c9b81a2cf003492de57ccaeca38a9055a4bec942be1a73d969dad974913199a6"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/justenoughcharacters.pw.toml"
hash = "f4cc3999b6f049871fa4201108cbc4f283353a8f99d7182b83403c760102119e"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "90a70141bcec839b6a1aa647c91f97bb7b33b6b9e6ce6b3b18a4113aa7dff636"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "d99d1c2d31ef8198c37c853676c71017ed2304d267d0590cbcb6c3658f674d0f"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "5a98133891a72e041e37bc235e86d495e488387f1628fc1377e6b5169dfbb8bd"
metafile = true

[[files]]
file = "mods/mafglib.pw.toml"
hash = "d921175a82cf60e7ebaa7f014f924b77a2f5ace44e81b309dc996c4c55b7455b"
metafile = true

[[files]]
file = "mods/mcwifipnp.pw.toml"
hash = "6a99ce3c12a689c1c9e5859ea4aff72bee5980792a59c94b83599d699d4bde3d"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "c9f8bce06b85e4dbfdaecc7d0930bf7f4fabccc7967f867b7eb7acb8dd5b77a7"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "82a0484217227dc92a79a12733b5a8051591c14c5aff1a55e7e675eb8c7eb72e"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "ab170eabaeec3e80c59e850a7d8aee32edfffd6a1e40e2c2f44575c69d122054"
metafile = true

[[files]]
file = "mods/modern-ui.pw.toml"
hash = "fb078f45d04576d994b31f76911eedf74aa6b4ca5ed177eedffd0853887cf97f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f7f96cba7b6d9da8113c00b50ed4ced2e12f8b2266dd1a5524427fde64afb2e1"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "679fa8f3b49b9ed3fbcb29d6ccdb99bce465faa01f9cec000464ac8d4fbe134f"
metafile = true

[[files]]
file = "mods/neoforge-carpet.pw.toml"
hash = "aed322aa8bdc69460c423989eea1413712dc9de8bc7764e65b914d1c3211a2e4"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "b849dfdaaa3e4ad635fb16595bfd6ae03b83de0c02f5b06faafb24cc33926f3f"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "85f965de3efa0ad66252b3540afff30d5a3cf8c9cb86692987830b8ae08489c5"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "59a9bbe68d16fdb5955d9775cca44093e43660d67b3ab4fba35a088db0ae5de5"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "fc10ab4fd98244dc1512adbfdb47bdc11fe43c860996cd4067834233fce9a562"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "ed55a23218dd66d083042069a68ecf7beebb374be76b79786f39b0ebeba8fc53"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "96d6ef91a108386ff19d45c201fa8c9fb8e0f3d4c3df3dff7396957a8350a419"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4dd7038889da90e145f9d074bec64a61aaae12dc57c875aa7ad99b8b2e07979b"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "bbdd40b650286973d44b1931d4b8c4bcc02b02f2c5583545709347503bd13057"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "32ee85be1b868a77453a16ab97c3f8e1a69d8ea7fff95ea0eeb1aea78b8d0eef"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "5b10404c7917952a2d651f353b99dea51f85df20606b4576d0552ab9dea6ce62"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "35c4484a3bd6b9055f3f944ed8bdc27fb8c62a385277b9e7f89fd19bccfa4191"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "817b4a47826bd99c69957fe07131d5704984f89fec96287cdc20c6fbe46100cf"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "5922477d07b7331f7659766c0d79d8c54ae2b77680f6473abef3199ee8296b8c"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b8c7497acbf4890b4609b6b20de7affdd3482fc99af975d9ff6b29c075e1d8a7"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1cf9cb3955b075664ea4fba13b47fe7160975740a28864983aebd53d39c1946e"
metafile = true

[[files]]
file = "mods/tweakerge.pw.toml"
hash = "2fe1a59e86b595ad5b8d25a0a9f5661b33071683a6ea5e23db146c030963e67e"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "f15d0baf68357fbb5c00ed2cb9a70496d15ec9b7b449ec28172529f8db9f9f65"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "3489f985776ee4df3fbf0866307c4e1fba065be55f747554971e2cb1edf6ad9d"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "1a592e56f6720b44d1031d2d715d454eff2099e915160c0c75f853ae8b314b15"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7e7b7624e041a1364971057d1c47f2b74730e191f142b73aa50223f95978dd96"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3b3d035b89519faccc4ddd8b0b4407ce96c0eb49068fe50a445d43a3baa8bea"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true

[[files]]
file = "options.txt"
hash = "51bc52c4032ac567731cc6dd0c2cec445e3514b3effeae5cdd1a77d17b29864e"

[[files]]
file = "resourcepacks/acaciachan-xaero-map-translation.pw.toml"
hash = "a763f371804ad4bd8d571f1a000fba61a6eaa2f295a347683fd10063110b4d12"
metafile = true

[[files]]
file = "resourcepacks/spbr.pw.toml"
hash = "1cc27f5b9dfe2a8cd3b8d43df0466b8086300e7cbd516785daf8910cee502f6e"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "575f72c3f1f10a74c40a1ebdb79c6e4c138ddc5e9309581f30297f7ea97d1bf2"
metafile = true

[[files]]
file = "shaderpacks/Sundial-Lite-277a82a.zip"
hash = "9e8a672257f3c0c33fb62109c5d7e235129049687f04c05ce12f8a4d01a3c624"

[[files]]
file = "shaderpacks/Sundial-Lite-MMCO_v0.2.18.zip"
hash = "e0f248b2ffd1170b4032a002746883d977751b4c9468e92c68a6d80d78af1bd6"

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "f4fb7685cf5f1f07eb5b07b0dd7ea211e46e249cb3a78237358d27c3db1dea2b"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true
