name = "LunarFox"
author = "OrzMiku"
version = "1.0.0+mc1.20.1-forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fe22a3544f81992d20608ee0f40103e01d63ce9b8933fb63c412ab7bbead82d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
