name = "LunarFox"
author = "OrzMiku"
version = "1.0.0+mc1.20.1-forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b3cc757dcabec9915dbfca3d8a650e4132c1237763928cf16fd85a81b282424"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
