name = "LunarFox"
author = "OrzMiku"
version = "0.0.0-alpha.2+mc1.21.11-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e103b5bf98b9d491b2b0b3be40b498e9802f0519da4d2cecf030e35baf474009"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
