name = "LunarFox"
author = "OrzMiku"
version = "0.0.0-alpha.3+mc1.21.11-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "656150595eb9b8f827ff21e128e031a783a63048ae822a5225f39a3f5af935db"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
