hash-format = "sha256"

[[files]]
file = "config/yosbr/config/DistantHorizons.toml"
hash = "7dafa18e710692bce1763cb36b73088ad7688039078eeb3ee396b800bb3360ce"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "32dc5f1d73b05e70f3fc5a18f58c5d81a095484a0f93a1da6d1883966ff4e296"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "6cc49905c1c8ff23683cfa9509bfd0576ddf2a315554845286f4f1eb2c4f85d9"

[[files]]
file = "config/yosbr/config/chatpatches.json"
hash = "0623905a25c9b6c8387f7a6a0256ea005f727c63c689d2cc7cc77f74e912f7e4"

[[files]]
file = "config/yosbr/config/defaultoptions/keybindings.txt"
hash = "7e6f498ca662b0a12b59331bd9746ca3d30c679c0f385bb0243cf3d7dda13e7f"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "7332aaf0769b81e5dfc0f4dc4fa5fcdc56e98811b75214e44ce2d06558e69712"

[[files]]
file = "config/yosbr/config/inventoryhud.json"
hash = "6b14ae9a50fe0dde599aa135d0820b67fbc352581e1b0b3a6f8e004c855a0095"

[[files]]
file = "config/yosbr/config/inventoryprofilesnext/inventoryprofiles.json"
hash = "8fa033afa83e6b5123c11bb293b0a5e632b4f76b2ca7d651350179fd435462c9"

[[files]]
file = "config/yosbr/config/iris_shader_folder.properties"
hash = "1a5d6fcabb22ac0718408b7ff05e298e719ffe855586df320bf0acbe6d3d0581"

[[files]]
file = "config/yosbr/config/litematica.json"
hash = "0186b89fc19e5b7b36902eed03061ff03530a15c86de6090c98f488bdaf51f73"

[[files]]
file = "config/yosbr/config/minihud.json"
hash = "435f7811c796b2352fee74985081994d69f881f9f0b6a0499ba39fbc40ee3f0b"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "72f8b0f992ed551eac5161bd4fb90f236814427371f33c7b22771fed05920a06"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "5cf6393f2eb20dc325b389aad51cab186c01a06956013138500de9235da31b0e"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "925c54884e5bb35cd962cc021219ee647f30dd68833109d396da9fb8545066f4"

[[files]]
file = "config/yosbr/config/tweakeroo.json"
hash = "61959e34930508cde414a11b937b544727ba3aa18712751b510ad5cec99eebeb"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "15eec0092ca5c54f97fc46953311e20e63a5eb6bca4672bfec9dae63f61cc456"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"
hash = "805d874877e6bb962ac09c250b3d2a084ec599b2242dd1fa36860623c2024890"

[[files]]
file = "config/yosbr/config/xaeroplus.txt"
hash = "b7c5f9eae2724e1da18af59e9369ddfd9d7b1c437ec6517603f22f0ff3bfcd3a"

[[files]]
file = "config/yosbr/config/xaeroworldmap.txt"
hash = "b0df40e07391a60294d7bffb9772cabe8096d61c41c8680fbfad927d3a6a5a6b"

[[files]]
file = "config/yosbr/options.txt"
hash = "632bc47136ef692686d301a242b43438906bb837714a23990da27d3c8bfdfbb2"

[[files]]
file = "icon.png"
hash = "7ed2443085370e3427bd3e803037356811af68ad3fc131947a89cc89f2103fc7"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7467a101c890769c5d0796e1a4d646074ef8f96c9c1d2995dbb0f3972ea49916"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "7749a788cd34e08e2280dc5e05db1bbf375d7a184d787f682f7df19709a754e3"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "659f7b849f370718cc5216c3de0fdc4863391f9889d00ebd4ccef8274ee7026d"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "d170ce4828b4b7fb7d21dc1dafd7e318e3f0cceea823f8d4f4e78f062baacc57"
metafile = true

[[files]]
file = "mods/axolotl-buckets.pw.toml"
hash = "2a138f455ec59c5be9d421370d8e168279fb94833c62d76db06431e429377be4"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "a2aa577e93491f2231af331570b5c96a384d260d8770bbd8271742567baaf2f7"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f34fa12fe7701cf0776fef1a1f1e2e3c7227f53302b3d87b7ff307f0446a68d2"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "94c3fc74cf184c9e5c597609dde733137f823bed718fcce32cdefaa040aa9977"
metafile = true

[[files]]
file = "mods/better-block-entities-1.0.0-0773bac.jar"
hash = "da49f3673bb95ede41d501ef08e3f7e2575c2443893595baceced2bead332e54"

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "6ef53c2c4e506e111b4bd7c1bc8804a5a7dcb2f6e3b79054575e73f6ce61ee94"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "ddb17abac95266f5845b2cc14acec1292e27f17da94acf423569b55f75ec8a7f"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "d74546a98e3af1867539d80bdf9d188968920a7df8e57ccb3b7a55b36a37eb7a"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "6d717e11f5a11194004d8879b5c1e46448394855211ce8ac1937ae40895f2c27"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "6088be62ff0bc4e93388ba995418a376a1b7dfd062cce84bc36349b34ffa4af6"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ee1808a7fb319d469dece5752cedb05dacb9afbe48021fa664f54b8c83fdc45"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "36cd95d46f6cf8fe027293599609ed9dc847ca245d59e085a5bd0fd87c0efe7d"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "783d509d7069d90ca34641f64936fc0eba7b974f0209e40a7ce915e4436e3309"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "82eed593663ed38d7f3fff58be659357f3ff54d8607b274b44274960f2458d85"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "da925d1159906a6c993fa4be167a48ae350d77daa1950a68135bf56c4e0dbb62"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "5ca99808c48e56205c8b02adfefa6489f9108eb25511f00721125cdc9fafe0e9"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "4bff7f89acd7892d306cf3e068d3f128c7a5170f3d40840364a3e7375ad34c1f"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "a43e3d76464a16015d62ba08d51da734f92377f0889c3984656d6d5739d284b2"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "2c31d52ada2aec45150617516523aaae57f30df0f8bb1ef1115e1825e5a89759"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5443c56a46d7fca84a1f96dc58315951a24cf8954f059aa35f213f28214d468d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "2a9e9968c598e234a84ccd9afc80a424d5c2ad9a37e4c85a0d36d06ddc9ebfa9"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "b5c07339bc334ddfe27120580cca09d71541a2f8230251a85284807ff0688a4c"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "3e3121bb346acbcda458a6bcd2e2d3564d54ef84a4fdbc802ed82447a80f2536"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "0df5b608f6521692c1434583a92f944e303881dbad0fcd98a5b5d37d7c22367a"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "c9babfbb0db58f9edfc38666af8ef4ce24fe0cd0594d3c421bb51410fb6c3fa2"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "dc14a906254d528b5ce82c0617c7e15d1ebbd17e4dcc2e852719fad60e8aa2b5"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "88164a8cb5574252a7acb82fe650c096b272f7912f00cd91c9d1dcc2a18549fa"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
hash = "15bce919514325447e487d260ec4458165fb4537ccadb9a0e740df4bcf3cb0ef"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5a6ee9ae2de75743aa027eb753ac9c3cb92305df67bde8fe2cefdd2df0eb49d7"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "7f5ae343f4e9e6e49c723311892b02351ff8031b2c3a1bf3d0e700bcd996ce90"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "b0366239de9d38bb6162e37b2bfd77a136732d35bc8e79688f4cffc18de17f70"
metafile = true

[[files]]
file = "mods/iris-shader-folder.pw.toml"
hash = "b615fd67bdae59fe637449a1e99ec1fd32f8a73e9a0f6079442ee54558633c23"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "e87a4eb7527e13fab94b671ce1d267cfc4d6093a3c3c1fbab7f135fb413727dc"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "979df86859d3a30ed4cae905f1e0b0bd2f06751fb9ed4de302a52c6285a0691c"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "55c7b1073141a49fbd6d3ba480bd95049f7978513e8261ec2bedab8e82409836"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "b9eadbeac742be0f77b95d3067c4760347452b690b8ae00268f4d5edc7ee8e70"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "47e38eeda17a991d3201448e71f68081893c8e7aee15b44088dc86eacfc8ca43"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "1bbb181ac406f7e655e87d3de443109c83a597c0784810a9fd48bb8fe09ba687"
metafile = true

[[files]]
file = "mods/mcwifipnp.pw.toml"
hash = "1a2791b229766967b04ee0701455b670a38f801cd2c49659980ee3c5234154ae"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "7ff35cde15036641fbd5c677962321fa5cfc4da8d5c71193b670d4f15a981577"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "ceadd493611f2ba6e1fd0d323db2200d7dfe99930631c3eda91279e7493e609e"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "2d373a1128cdb01a77053c64d5d6a64cf76c2d68da0529b2cc0f2dd6f8371767"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "b261880bd245c83c51b729199452da12b0766a4aa0210fc79d0c48161cbfcc49"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "d50b7be11b0ef674f0f5b7b4307dc4919683fa63bdc72703912258a528398e61"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "dc24a4cc0ad484d6593997c197ea602fac4d98c45dab0de6421e704c3851acd9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "6dbf0e2efe99954db4669dc8e7007c9395c3613ae94f740f2ffa52f6740c35fd"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "958d770c8024a7c901315c786f6060554b5583ae302068526766e42c31b5f604"
metafile = true

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "b5cb84815833d2b87d74c5056428ccb267ec68216495022041a799f9b85c6d07"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "368cc4f1195320c978639963acadbf685118b9f69cf0ef899b8ff8a32f204316"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "060ac39885ce347a5d51c4137d4968e5cb7dae2dfa5f9554e0161391d01ceb52"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "1d0b4cb5d19919e7c63ece2bda6e312ca80f266880e6472182cda993d70ed8fb"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6563af8f8937ede110303ee1437499892061d824182139a92e7a1fd6eac168d7"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1600b1e64b297d68bafb4f5e5eeef08117645ac24922696da10c711ae587c06b"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "72be271710b8a54e18cb7c0dfc2b8534ce3b5f3a6735928ca34979fc94ea992b"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "8e0dd3e606968ee0aea0d95b42a472ea921d5f1e754eec4bef2fc005f2e7f663"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "5ae220cfbb26641c68740ad0166c78f353680886fc28087e63bf07280a47ddbb"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "4b0cb4b61e8bdb342fac44e7d09c07a33b4cb7e4627b29de739a7f095754641d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4f57108f9e1c6281cfdaf3812e6bc2a2f16609a845c9912218ada90b1603e1b3"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "2d27a6e7c7e28a33b4e3d85106f80fd6629f060ec31a8be525f1c2ac9f769cf1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "9a0d53217201df1a02fd2c4db95b61136da9b94e734876fe63116f4811538ed5"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "7c8590d2228acc18559c18767b83781cea7318cf36edbf0ee01aeca4a814c4b1"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "c5092ec9a074c3afcc2312c985d0829e023dcfa3524597ec1c4902359d5c78dc"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "97da8aa107b5934bc6a37756a8ff3458565666c4433dce7f7021db6d238e8100"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "1750b72e8ece77b5676ed18ffce81d0fd4df89e8bbde63ef8cc328df87bb9277"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "45d1f440945a61fd298d497725a3b2aa8fac958102d0ec5797f7c2f2a4a3d5e9"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "665729108397fa6fa88132dcb3f82ef3505617f3bc979ec6884608fce949cc5f"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "993390d4661a77aa83c8416f75addfccaf7cee0a7a7311a21742b2036700b5ac"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "53c8bc02c9b10610c43fc29127039036217e33a95ab2ea2d6ac291987266ef89"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true

[[files]]
file = "resourcepacks/acaciachan-xaero-map-translation.pw.toml"
hash = "a763f371804ad4bd8d571f1a000fba61a6eaa2f295a347683fd10063110b4d12"
metafile = true

[[files]]
file = "resourcepacks/spbr.pw.toml"
hash = "18929e72a24ded428508309980c987dbbdcceaf6928d02df80c21c0bbe988572"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "575f72c3f1f10a74c40a1ebdb79c6e4c138ddc5e9309581f30297f7ea97d1bf2"
metafile = true

[[files]]
file = "shaderpacks/Sundial-Lite-277a82a.zip"
hash = "9e8a672257f3c0c33fb62109c5d7e235129049687f04c05ce12f8a4d01a3c624"

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "f4fb7685cf5f1f07eb5b07b0dd7ea211e46e249cb3a78237358d27c3db1dea2b"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true
