name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.21.10_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04dd14de2ce221e0c480b5c2343a2fba548b272e836277d7f7a51c8ac62dd184"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
