name = "LunarFox"
author = "OrzMiku"
version = "1.2.4+mc1.21.10-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "152a481605eec591a5b39626f2c0cfdbf28fe719a5e899c594456145a4004d9a"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
