name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.21.10_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21a07c885767e14f64a411d5aa970c1551f20e2a7a6bf1d150e487a7eadfbd2a"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
