name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.21.10-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2826f5cd0e0f285815f45ddd025963463cbcf43aa1e5b60369f530674dfebd99"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
