name = "LunarFox"
author = "OrzMiku"
version = "1.2.4+mc1.21.10-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5a4039f6069a6c8d2098c7274c3d4068f0bb02bc3e3a12c9abab51bd1eef155"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
