name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.21.10-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d0d1fcd373c6646374465574712cc5560448986e58178030bbada9f60d30d34"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
