name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.21.10-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53d341cf6b07da6918751dfe0e783c2f0e1e1b65bbe9b6e55bbf249574d8dd9e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
