hash-format = "sha256"

[[files]]
file = "config/yosbr/ViaFabricPlus/settings.json"
hash = "9737f5d0ae37f5e4bf9a054be38c4c99a8bc0db61544bbc27c14011c12101a24"

[[files]]
file = "config/yosbr/config/DistantHorizons.toml"
hash = "7dafa18e710692bce1763cb36b73088ad7688039078eeb3ee396b800bb3360ce"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "58c9e639e6458fdcdd201f080187df717242571a32d6406479b7624468ca66e9"

[[files]]
file = "config/yosbr/config/acceleratedrendering-client.toml"
hash = "e7939689f07241a61205ece2eb2bbb957f24b56204c6f905db6f4871a10cc4a5"

[[files]]
file = "config/yosbr/config/betteradvancements.json"
hash = "e5f6ace68c722b5e4ea32f9935ca0b8dfbea1d22f1b8599a339bde0456605973"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "6cc49905c1c8ff23683cfa9509bfd0576ddf2a315554845286f4f1eb2c4f85d9"

[[files]]
file = "config/yosbr/config/chatpatches.json"
hash = "0623905a25c9b6c8387f7a6a0256ea005f727c63c689d2cc7cc77f74e912f7e4"

[[files]]
file = "config/yosbr/config/defaultoptions/keybindings.txt"
hash = "478c894e20be669902210726813d0cf180680774a1bc8984e2c75c170c6e7e25"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/inventoryhud.json"
hash = "6b14ae9a50fe0dde599aa135d0820b67fbc352581e1b0b3a6f8e004c855a0095"

[[files]]
file = "config/yosbr/config/inventoryprofilesnext/inventoryprofiles.json"
hash = "8fa033afa83e6b5123c11bb293b0a5e632b4f76b2ca7d651350179fd435462c9"

[[files]]
file = "config/yosbr/config/iris_shader_folder.properties"
hash = "1a5d6fcabb22ac0718408b7ff05e298e719ffe855586df320bf0acbe6d3d0581"

[[files]]
file = "config/yosbr/config/masa_gadget_mod.json"
hash = "e06a95ec2a838775dfeaa364f17be6a8f4521138055f8ccee8ff59f66d7464fa"

[[files]]
file = "config/yosbr/config/minihud.json"
hash = "435f7811c796b2352fee74985081994d69f881f9f0b6a0499ba39fbc40ee3f0b"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "5cb23400baacc7b307f687a19b966c0aa6861e7b157167dc02fd416e5a9219fa"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "5cf6393f2eb20dc325b389aad51cab186c01a06956013138500de9235da31b0e"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/config.json5"
hash = "c550f46ad5ec34377e2b77a84f553ef1ac02bd9515219a8b4c0239ce036a966a"

[[files]]
file = "config/yosbr/config/sodium-mixins.properties"
hash = "fa47ad234f2b53c2366ea8df83d5485f36d5129f228413416212b6f0ca2ba856"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "925c54884e5bb35cd962cc021219ee647f30dd68833109d396da9fb8545066f4"

[[files]]
file = "config/yosbr/config/tweakeroo.json"
hash = "61959e34930508cde414a11b937b544727ba3aa18712751b510ad5cec99eebeb"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "15eec0092ca5c54f97fc46953311e20e63a5eb6bca4672bfec9dae63f61cc456"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"
hash = "805d874877e6bb962ac09c250b3d2a084ec599b2242dd1fa36860623c2024890"

[[files]]
file = "config/yosbr/config/xaeroplus.txt"
hash = "b7c5f9eae2724e1da18af59e9369ddfd9d7b1c437ec6517603f22f0ff3bfcd3a"

[[files]]
file = "config/yosbr/config/xaeroworldmap.txt"
hash = "b0df40e07391a60294d7bffb9772cabe8096d61c41c8680fbfad927d3a6a5a6b"

[[files]]
file = "config/yosbr/options.txt"
hash = "0cc7e907a5ed861cc5c372d763b7bc8ee6abae231bd4cc99ebac8751540d44d3"

[[files]]
file = "icon.png"
hash = "7ed2443085370e3427bd3e803037356811af68ad3fc131947a89cc89f2103fc7"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "ea430db88d8f190a053e4f3c662d2a59b6a7508778525034f2b20037ee074aec"
metafile = true

[[files]]
file = "mods/accrelatedrendering-refabricated.pw.toml"
hash = "34ea97a2c2df538e7474c4c25beaedd1205c1689d2f059ef35ce5f7fc93ccfeb"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "e94fd2f80b6029f19fb0c68d5bbf443a21645af0d668c5a544e3b3f23508fb61"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "786d07a05c5cc3ae4b2ee78aa95555017a411450a7a0e2328660b9ce3a47943a"
metafile = true

[[files]]
file = "mods/axolotl-buckets.pw.toml"
hash = "b89ac30aa92e1378679d010fae0fbf0834acca099aea381c92123e3c62d40c33"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7eb6b5ee57865d6221be3c428f5a0c4e449f4c86920e9f8736b4f755d7822edf"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "71dc04da11ad8f4a5d88db5505132a654ce033f05dc2fa4bb7aa28a42762086f"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "036bd1f08a582f2a38809e3ab65720d5e04d84fcc1c7b8558d6888c319e18527"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "333dfa2b93c688ce5f9f685f77cb62e5df8b9c8d21a2c4dd4eb9232aa85dccff"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "8f54b2270c2d87b56a73b4355305cc4a4dd277330cad97d137b98073ec0d8e83"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "449d548b749af0fa7770496ebf513d97075e2a3493bda9c7a45a63ba94792d0f"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "6d7c5793f88c52421dc11f48b3bf12400e7a451b9297e80fe33b776cc2af2c1d"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "444dc7b515acd2e5a5b399c78fe89758f43bfe962a453472ad18a50193eae8b6"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "d6878871a07870b33821beed20118368e779c17574062d5d771eb38b9403e875"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "62392ad801b58819a5821bdbde21686cf338cf0416ece1721db551f8d2497db3"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "64a244469b7ce7be7e6ceabedd69d17e573a0b92d6e29c661fc6c490afa965d8"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "f912004cc3c195008c32edf5ad4108639eb36530221886034cdd03b7916a220a"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "1173755b093b4f9a8aca00520d87bc35178fe19c54e59debe5c48d0c9063b91c"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "76f36ebd83c7957f21782f2b97e2dcf304abcbd81780bfcd0e48f19477d3702e"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "d2e1ad62031e3700de73a87957a4acca747436a4135da695705cb5d293aa0890"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e81c635602878f92af9a9c11b92481b25c7aaf3f68cd015dabf5f67201886401"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "ff674220aeb9395349903de7d40a1af1bbcbc0aa9182c193df50b21225065709"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "b886b1761e9a0e36cfc351c3e8cd3455fbe35143ade876c97cc43d02b07b061d"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c5ea75feae4d340856611f78a29e6f1f0b7e707bfe43847f11d25fac1769dee7"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "f1d9c0910c3172c83058cc6d9af49e9b8dd9a6e410b0113e41077a373a0646a0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "58a487d9e3761d18f529cf141c873ea054e8f26c5e90601a3c8cf60fc723b22d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "91f45174d8627de2d04922bcf83b4b7c31188fbfc748240fcca27ea4f3282e93"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "53588e917d3908a03b747b7d2b82a0c20205bf953023f7b10e4cd157d453b606"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "3e3121bb346acbcda458a6bcd2e2d3564d54ef84a4fdbc802ed82447a80f2536"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "a87febb1a064e3f9e9d7b3a2855f047356f5edd2fd520b1aade632b8bbe4da12"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "d38f50aad915b4c2f6ee7dfe1a480970def9dd312932504c4f008cbe17988306"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "fff1e00559f13c092b17fa83804279cf70191d7a99a4a98a4eb6bb30ac9a78db"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "29d41095d30271247f296402d3e50d8ce060acf77808efcbe25de0ec84e76975"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "4449401b59481016fa2a66d6e749795129160cb1ab3e7932e15033c6b5815455"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "26aabc12649a729a2d5c593fd70ed50933a9fe9c7d16d2bdffa44a2165aa59e1"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "0f88e46eb7b6487e139e4cf9e75c3b6c2764ffea3a222655798a893399bdfa1a"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
hash = "b085a13f441287ee000f3d17b49755741ed738a2a296fe349c79c01ed9d81350"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "58ace6ddc01192bd96668e2a833568083f34b0808645e056c0f1e0716f63abe5"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "cc5ce2c69f275f245fccbb9f673f5b6711175034bdf41f48cfb672e652ea984b"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "e4a36696e1c12e76ee1cf9da4682770edd2d404cef742db8ecb306455b3f0ef4"
metafile = true

[[files]]
file = "mods/iris-shader-folder.pw.toml"
hash = "b615fd67bdae59fe637449a1e99ec1fd32f8a73e9a0f6079442ee54558633c23"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "d56556655c08d4f7397a6f0473decc5f78bb48608df2ae85fc2fd0faaf847fab"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/justenoughcharacters.pw.toml"
hash = "0d45b133838f950734afb95a799fdb5a98e343bd2bfef793571ced939b325422"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "d6be91dc0a2aca23ee640818d8a8295c85ddb2db6e0413669ecac9600b01eef0"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "cc298019c2d3a47a97e72363b942fe408e5ecb7ff476fe08155793f2f1578317"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "8a786b5c9b67df34894f944708f722ef3ade67ea3c3aa4997144314c26f847f7"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/magiclib.pw.toml"
hash = "8b8e5357a733b05d0773f3acd4f4cdf877c356543fe7e8948ce1fa63ee46b443"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "6bfb82960a27af2c360036e01c0131c3ad9c778b4ba5e3df51bafe4f175317db"
metafile = true

[[files]]
file = "mods/masa-gadget.pw.toml"
hash = "c9ba6989c2601cbfea69ea0544dd6288e328c977a750e76d7c30be8c152b4961"
metafile = true

[[files]]
file = "mods/mcwifipnp.pw.toml"
hash = "ab8f35c350890e95cec1c453b96735422b1a05408f28c7501b432a443f5864ba"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "a387dcfe8d66bcde451407d5608af67e95720dea13d94a20e13ad5340f6bec6e"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "f40488b90039380bde4615baca056eaec3afb62defccd7301a15af1c602970c3"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "e5bf9057e940554a9d6f653af4118d64f09040871c7ada034a697d630fedcab5"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "435267c3230ba1439f50fa32c3ed3993a4123f870681451aa95acdde5d52622e"
metafile = true

[[files]]
file = "mods/modern-ui.pw.toml"
hash = "786d02da913000fe76b455aa87a4c2567d555e37255202090a6d955d774c4903"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f43c82e3cc6079291ddae81445c703905b6c670dd43f444e47f5cd817944e822"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "dbb344ad3e49c36d167fa05b6c5f674794306b1727220e8720d767264aee497f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "f4b9d7acc345b8df6dd13e19b36658cbca476abdee703ee6f38c66d33e8fa763"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "a0b2b689e7e6eb10cd342da48dd605cfbe09d782790a42089f31835a54e37b1a"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "d38f50aad915b4c2f6ee7dfe1a480970def9dd312932504c4f008cbe17988306"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9ed765da71f977af16c71b3ff56356dea5a149d9626277e4d4868941f8efa1b0"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "fc10ab4fd98244dc1512adbfdb47bdc11fe43c860996cd4067834233fce9a562"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "da5c3835be36d509d4c51f43f943b5ed672885dee1d6e99ebbfc5fb9187b3560"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "9ad63ddb4586e2650aca101712f9d0f5efa14e5959965cb6e6fc6ad300e8c3ee"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "f58d2d24534aff39d9d1cbfa0dffa97fcc01af5bbabc75e486b1f64a5235f1e5"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "a9769ced0531122518321833966d375196753db1c3a47b975aed4bb6837fae7a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a1eff7b33a54586b6989c7bfd89992f9d315f1c656b7596649d9af7017c6af7b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "657ff0025d408f1021309ce5c759821d1f48e397811cc0da6f0b0400827896fa"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "058d9d83b502682366ba75fb00b50d5c8a7e7335722ced0407579ae3a25dd6f8"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "83164a6af3923e28cadf9d404f059bf74aa4f0842fc1ca0f6e7cf1e686044875"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "964da9ed4bdd490258a05d249e13b8d90d82f71591c793bc93e29840e4e9fe1b"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "830270b8e5a34f5621720ae09c4cf716a65d8003a30d585c8b817aba1fde9ac8"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "83cf89128bfc6d4a5d1da20565e461f89183127d5960935c1f783ba38b0cb53c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "bf3a50b4962319fdc9bcdb9b56aa5af1d674a16740c36f5732cb8fe91aafb46f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "98553c2d49ef3a888954f24b7c49fe3442c01fd4fc1f1ed52c5898ed29d29d3b"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "e0047e26d3d4a5a290dc150e9a7c5c5f64cde9e6a0538eaa6f6060374349700f"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "5267cd0ff94e2695e70720e94c8940045a6a7371c89c3adcad48660b303698dd"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "caa507edc23c21df56cda8b40d30d74eaa999b19bf2fe4e2b53cf9a256e1ac76"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "47634b4eedae148767c2dc94236c8f07054a533139400404d74deaf088348a08"
metafile = true

[[files]]
file = "mods/title-fixer.pw.toml"
hash = "10b6a4137e030a03598f86b28fe03c9001d6eb2accb2668d5d68d7eca9a7f575"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "9b51c35206dd74dac90e3cc3f2ff9e1c45552500e6a01be183bc64260a0e5815"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "bcc5eac5501c4c51a77d3f128758f00f75ef37a233b110f93e00c495b61d4976"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "74906aa6f2f33b0391252d50b1d446d2ad2df4d6ca1026b941e90cc579a0692b"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "5fa91b45e2fdca864ceb74134974d9a668081b052adde4742db35494e691777e"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "ff06f715857663fbe7ab260258db09bdf408e63a203faad1032e7b0ec9d51d25"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "34b672500b3219fa67f776c0e2c69854746034e541a2d17bef34ae90e38f1a03"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "bbde815d37f2d9e01be4c39266bc2219222384737b4e6958a0047397a31c80fb"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "1bb9b2e75c6934b1f18648e9b37e20abcf6a4a2547c7cdb0abe88407267e0c10"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true

[[files]]
file = "resourcepacks/acaciachan-xaero-map-translation.pw.toml"
hash = "a763f371804ad4bd8d571f1a000fba61a6eaa2f295a347683fd10063110b4d12"
metafile = true

[[files]]
file = "resourcepacks/spbr.pw.toml"
hash = "1cc27f5b9dfe2a8cd3b8d43df0466b8086300e7cbd516785daf8910cee502f6e"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "575f72c3f1f10a74c40a1ebdb79c6e4c138ddc5e9309581f30297f7ea97d1bf2"
metafile = true

[[files]]
file = "shaderpacks/Sundial-Lite-277a82a.zip"
hash = "9e8a672257f3c0c33fb62109c5d7e235129049687f04c05ce12f8a4d01a3c624"

[[files]]
file = "shaderpacks/Sundial-Lite-MMCO_v0.2.18.zip"
hash = "e0f248b2ffd1170b4032a002746883d977751b4c9468e92c68a6d80d78af1bd6"

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "f4fb7685cf5f1f07eb5b07b0dd7ea211e46e249cb3a78237358d27c3db1dea2b"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true
