name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.20.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be50c8548cbe5dee9b7f7de4d76e9c591d17f28b235c1a89c9566892b1a90022"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
