name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.20.1_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c851b8d6f9289a327af4fda6e83eeda621733f27da6633058f27533841edd204"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
