name = "LunarFox"
author = "OrzMiku"
version = "1.2.3+mc1.20.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b11983100789d76ad52c51115b12d9e32bb8f02d8f8f0822e81960e7835d6b14"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
