name = "LunarFox"
author = "OrzMiku"
version = "1.2.4+mc1.20.1-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "242484f01bfa31b8dabedbcd213a89c97e4b2c257c41c40c3c1f69a42fff54d9"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
